[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Netmask
"""
prompt.distractors = [
    """
    Dotted Decimal: 255.255.255.252
    Dotted Binary: 11111111.11111111.11111111.11111100
    """,
    """
    Dotted Decimal: 255.255.255.248
    Dotted Binary: 11111111.11111111.11111111.11111000
    """
]
answer.answer = """
    Dotted Decimal: 255.255.255.252 
    Dotted Binary: 11111111.11111111.11111111.11111100
"""
id = "affb7a35-7612-4934-b549-aea10e255007"


[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Calculate the Number of Subnets and Hosts per Subnet
"""
prompt.distractors = [
"4",
"2",
"8",
"16"
]
answer.answer = "2"

context = """

- With /30, we have 2 host bits remaining.
- Number of subnets created: 2⁶ = 64 possible subnets.
- Hosts per subnet: 2² − 2 = 2 usable addresses per subnet (subtracting 2 for network and broadcast addresses).

"""
id = "55f164c2-149b-4172-9eab-0222a8bec330"



[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Determine the next Subnet ID & Ranges for 198.51.100.128/30
"""
prompt.distractors = [
    """
    - Subnet ID: 198.51.100.132/30
    - Range: 198.51.100.132 - 198.51.100.135
    - Usable Host Range: 198.51.100.133 - 198.51.100.135
    """,
    """
    - Subnet ID: 198.51.100.136/30
    - Range: 198.51.100.136 - 198.51.100.139
    - Usable Host Range: 198.51.100.137 - 198.51.100.138
    """
]
answer.answer = """
    - Subnet ID: 198.51.100.132/30
    - Range: 198.51.100.132 - 198.51.100.135
    - Usable Host Range: 198.51.100.133 - 198.51.100.134
"""
id = "85127cb6-7bfd-49de-adbc-07a6857644d0"