[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Netmask
"""
prompt.distractors = [
    """
    Dotted Decimal: 255.255.248.0
    Dotted Binary: 11111111.11111111.11111000.00000000
    """,
    """
    Dotted Decimal: 255.255.240.0
    Dotted Binary: 11111111.11111111.11110000.00000000
    """
]
answer.answer = """
    Dotted Decimal: 255.255.224.0 
    Dotted Binary: 11111111.11111111.11100000.00000000
"""
id = "affb7a35-7612-4934-b549-aea10e255006"


[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Calculate the Number of Subnets and Hosts per Subnet
"""
prompt.distractors = [
"8192",
"4096",
"2048",
"1024"
]
answer.answer = "8190"

context = """

- With /19, we have 13 host bits remaining.
- Number of subnets created: 2⁵ = 32 possible subnets.
- Hosts per subnet: 2¹³ − 2 = 8190 usable addresses per subnet (subtracting 2 for network and broadcast addresses).

"""
id = "55f164c2-149b-4172-9eab-0222a8bec329"



[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Determine the 2nd Subnet ID & Ranges for 172.16.0.0/19
"""
prompt.distractors = [
    """
    - Subnet ID: 172.16.0.0/19
    - Range: 172.16.0.0 - 172.16.31.255
    - Usable Host Range: 172.16.0.1 - 172.16.31.254
    """,
    """
    - Subnet ID: 172.16.16.0/19
    - Range: 172.16.16.0 - 172.16.80.255
    - Usable Host Range: 172.16.16.1 - 172.16.80.254
    """
]
answer.answer = """
    - Subnet ID: 172.16.32.0/19
    - Range: 172.16.32.0 - 172.16.63.255
    - Usable Host Range: 172.16.32.1 - 172.16.63.254
"""
id = "85127cb6-7bfd-49de-adbc-07a6857644cf"