[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Netmask
"""
prompt.distractors = [
    """
    Dotted Decimal: 255.255.255.224
    Dotted Binary: 11111111.11111111.11111111.11111000
    """,
    """
    Dotted Decimal: 255.255.255.240
    Dotted Binary: 11111111.11111111.11111111.11110000
    """
]
answer.answer = """
    Dotted Decimal: 255.255.255.224 
    Dotted Binary: 11111111.11111111.11111111.11100000
"""
id = "affb7a35-7612-4934-b549-aea10e255004"


[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Calculate the Number of Subnets and Hosts per Subnet
"""
prompt.distractors = [
"32",
"16",
"8",
"4"
]
answer.answer = "30"

context = """

- With /27, we have 5 host bits remaining.
- Number of subnets created: 2³ = 8 possible subnets.
- Hosts per subnet: 2⁵ − 2 = 30 usable addresses per subnet (subtracting 2 for network and broadcast addresses).

"""
id = "55f164c2-149b-4172-9eab-0222a8bec327"



[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Determine the 3rd Subnet ID & Ranges for 192.168.10.0/27
"""
prompt.distractors = [
    """
    - Subnet ID: 192.168.10.64/27
    - Range: 192.168.10.0 - 192.168.10.31
    - Usable Host Range: 192.168.10.1 - 192.168.10.30
    """,
    """
    - Subnet ID: 192.168.10.96/27
    - Range: 192.168.10.96 - 192.168.10.127
    - Usable Host Range: 192.168.10.97 - 192.168.10.126
    """
]
answer.answer = """
    - Subnet ID: 192.168.10.64/27
    - Range: 192.168.10.64 - 192.168.10.95
    - Usable Host Range: 192.168.10.65 - 192.168.10.94
"""
id = "85127cb6-7bfd-49de-adbc-07a6857644cd"