[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Netmask
"""
prompt.distractors = [
    """
    Dotted Decimal: 255.226.0.0
    Dotted Binary: 11111111.11110000.00000000.00000000
    """,
    """
    Dotted Decimal: 255.255.255.0
    Dotted Binary: 11111111.11111111.11111111.00000000
    """
]
answer.answer = """
    Dotted Decimal: 255.255.0.0 
    Dotted Binary: 11111111.11111111.00000000.00000000
"""
id = "affb7a35-7612-4934-b549-aea10e255003"


[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Calculate the Number of Subnets and Hosts per Subnet
"""
prompt.distractors = [
"65536",
"32768",
"16384",
"8192"
]
answer.answer = "65534"

context = """

- With /16, we have 16 host bits remaining.
- Number of subnets created: 2⁸ = 256 possible subnets.
- Hosts per subnet: 2¹⁶ − 2 = 65534 usable addresses per subnet (subtracting 2 for network and broadcast addresses).

"""
id = "55f164c2-149b-4172-9eab-0222a8bec326"


[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Determine the 3rd Subnet ID & Ranges for 10.0.0.0/16
"""
prompt.distractors = [
    """
    - Subnet ID: 10.0.1.0/16
    - Range: 10.0.1.0 - 10.0.1.255
    - Usable Host Range: 10.0.1.1 - 10.0.2.254
    """,
    """
    - Subnet ID: 10.0.3.0/16
    - Range: 10.0.3.0 - 10.0.3.255
    - Usable Host Range: 10.0.3.1 - 10.0.3.254
    """
]
answer.answer = """
    - Subnet ID: 10.0.2.0/16
    - Range: 10.0.2.0 - 10.0.2.255
    - Usable Host Range: 10.0.2.1 - 10.0.2.254
"""
id = "85127cb6-7bfd-49de-adbc-07a6857644cc"
