[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Netmask
"""
prompt.distractors = [
    """
    Dotted Decimal: 255.255.252.0
    Dotted Binary: 11111111.11111111.11111100.00000011
    """,
    """
    Dotted Decimal: 255.255.255.0
    Dotted Binary: 11111111.11111111.11111111.00000000
    """
]
answer.answer = """
    Dotted Decimal: 255.255.252.0 
    Dotted Binary: 11111111.11111111.11111100.00000000
"""
id = "affb7a35-7612-4934-b549-aea10e255002"


[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Calculate the Number of Subnets and Hosts per Subnet
"""
prompt.distractors = [
"1024",
"512",
"256",
"128"
]
answer.answer = "1022"

context = """

- With /22, we have 10 host bits remaining.
- Number of subnets created: 2² = 4 possible subnets.
- Hosts per subnet: 2¹⁰ − 2 = 1022 usable addresses per subnet (subtracting 2 for network and broadcast addresses).

"""
id = "55f164c2-149b-4172-9eab-0222a8bec325"



[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Determine the 3rd Subnet ID & Ranges for 172.16.0.0/22
"""
prompt.distractors = [
    """
    - Subnet ID: 172.16.4.0/22
    - Range: 172.16.4.0 - 172.16.7.255
    - Usable Host Range: 172.16.4.1 - 172.16.7.254
    """,
    """
    - Subnet ID: 172.16.8.0/22
    - Range: 172.16.8.0 - 172.16.11.255
    - Usable Host Range: 172.16.8.1 - 172.16.11.254
    """
]
answer.answer = """
    - Subnet ID: 172.16.4.0/22
    - Range: 172.16.4.0 - 172.16.7.255
    - Usable Host Range: 172.16.4.1 - 172.16.7.254
"""
id = "85127cb6-7bfd-49de-adbc-07a6857644cb"